var apexam;
(function (apexam) {
    apexam.apexamLayout = {
        home: ' < h1 class="my-4 text-center text-lg-left" > 試験メニュー < /h1>'
            + ''
            + '      <div class="row text-center text-lg-left">'
            + ''
            + '        <div class="col-lg-3 col-md-6 col-xs-6">'
            + '          <a href="#" class="d-block mb-4 h-100" id="ap01" retrun false;>'
            + '            <img class="img-fluid img-thumbnail" src="images/image_ap01.png" alt="image_ap01">'
            + '          </a>'
            + '        </div>'
            + '        <div class="col-lg-3 col-md-6 col-xs-6">'
            + '          <a href="#" class="d-block mb-4 h-100" id="es01" retrun false;>'
            + '            <img class="img-fluid img-thumbnail" src="images/image_es01.png" alt="image_es01">'
            + '          </a>'
            + '        </div>'
            + '        <div class="col-lg-3 col-md-6 col-xs-6">'
            + '          <a href="#" class="d-block mb-4 h-100">'
            + '            <img class="img-fluid img-thumbnail" src="http://placehold.it/600x600" alt="">'
            + '          </a>'
            + '        </div>'
            + '        <div class="col-lg-3 col-md-6 col-xs-6">'
            + '          <a href="#" class="d-block mb-4 h-100">'
            + '            <img class="img-fluid img-thumbnail" src="http://placehold.it/600x600" alt="">'
            + '          </a>'
            + '        </div>'
            + '        <div class="col-lg-3 col-md-6 col-xs-6">'
            + '          <a href="#" class="d-block mb-4 h-100">'
            + '            <img class="img-fluid img-thumbnail" src="http://placehold.it/600x600" alt="">'
            + '          </a>'
            + '        </div>'
            + '        <div class="col-lg-3 col-md-6 col-xs-6">'
            + '          <a href="#" class="d-block mb-4 h-100">'
            + '            <img class="img-fluid img-thumbnail" src="http://placehold.it/600x600" alt="">'
            + '          </a>'
            + '        </div>'
            + '        <div class="col-lg-3 col-md-6 col-xs-6">'
            + '          <a href="#" class="d-block mb-4 h-100">'
            + '            <img class="img-fluid img-thumbnail" src="http://placehold.it/600x600" alt="">'
            + '          </a>'
            + '        </div>'
            + '        <div class="col-lg-3 col-md-6 col-xs-6">'
            + '          <a href="#" class="d-block mb-4 h-100">'
            + '            <img class="img-fluid img-thumbnail" src="http://placehold.it/600x600" alt="">'
            + '          </a>'
            + '        </div>'
            + '      </div>',
        esMenu: '      <h1 class="my-4 text-center text-lg-left">過去問一覧</h1>'
            + ''
            + '      <div class="row text-center text-lg-left">'
            + ''
            + '        <div class="col-lg-3">'
            + '            <div class="dropdown show">'
            + '              <a class="btn btn-secondary dropdown-toggle btn-block" href="https://example.com" id="dropdownMenuLink1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">'
            + '                午前II試験（年度別）'
            + '              </a>'
            + '              <div class="dropdown-menu btn-block text-center" aria-labelledby="dropdownMenuLink1">'
            + '                <a class="dropdown-item" href="#" id="29SESAM2" retrun false;>2017年春期</a>'
            + '                <a class="dropdown-item" href="#" id="28SESAM2" retrun false;>2016年春期</a>'
            + '                <a class="dropdown-item" href="#" id="27SESAM2" retrun false;>2015年春期</a>'
            + '                <a class="dropdown-item" href="#" id="26SESAM2" retrun false;>2014年春期</a>'
            + '                <a class="dropdown-item" href="#" id="25SESAM2" retrun false;>2013年春期</a>'
            + '                <a class="dropdown-item" href="#" id="24SESAM2" retrun false;>2012年春期</a>'
            + '                <a class="dropdown-item" href="#" id="23SESAM2" retrun false;>2011年春期</a>'
            + '              </div>'
            + '            </div>'
            + '        </div>'
            + '        <div class="col-lg-3">'
            + '            <div class="dropdown show">'
            + '              <a class="btn btn-secondary dropdown-toggle btn-block" href="https://example.com" id="dropdownMenuLink2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">'
            + '                準備中 午後I試験（年度別）'
            + '              </a>'
            + '              <div class="dropdown-menu btn-block text-center" aria-labelledby="dropdownMenuLink2">'
            + '                <a class="dropdown-item" href="#" id="29SESPM1" retrun false;>2017年春期</a>'
            + '                <a class="dropdown-item" href="#" id="28SESPM1" retrun false;>2016年春期</a>'
            + '                <a class="dropdown-item" href="#" id="27SESPM1" retrun false;>2015年春期</a>'
            + '                <a class="dropdown-item" href="#" id="26SESPM1" retrun false;>2014年春期</a>'
            + '                <a class="dropdown-item" href="#" id="25SESPM1" retrun false;>2013年春期</a>'
            + '                <a class="dropdown-item" href="#" id="24SESPM1" retrun false;>2012年春期</a>'
            + '                <a class="dropdown-item" href="#" id="23SESPM1" retrun false;>2011年春期</a>'
            + '              </div>'
            + '            </div>'
            + '        </div>'
            + '        <div class="col-lg-3">'
            + '            <div class="dropdown show">'
            + '              <a class="btn btn-secondary dropdown-toggle btn-block" href="https://example.com" id="dropdownMenuLink3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">'
            + '                利用できません'
            + '              </a>'
            + '              <div class="dropdown-menu btn-block text-center" aria-labelledby="dropdownMenuLink3">'
            + '                <a class="dropdown-item" href="#" onclick="alert()" retrun false;>2017年春期</a>'
            + '                <a class="dropdown-item" href="#" onclick="alert()" retrun false;>2016年春期</a>'
            + '                <a class="dropdown-item" href="#" onclick="alert()" retrun false;>2015年春期</a>'
            + '                <a class="dropdown-item" href="#" onclick="alert()" retrun false;>2014年春期</a>'
            + '                <a class="dropdown-item" href="#" onclick="alert()" retrun false;>2013年春期</a>'
            + '                <a class="dropdown-item" href="#" onclick="alert()" retrun false;>2012年春期</a>'
            + '                <a class="dropdown-item" href="#" onclick="alert()" retrun false;>2011年春期</a>'
            + '              </div>'
            + '            </div>'
            + '        </div>'
            + '        <div class="col-lg-3">'
            + '            <div class="dropdown show">'
            + '              <a class="btn btn-secondary dropdown-toggle btn-block" href="https://example.com" id="dropdownMenuLink4" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">'
            + '                利用できません'
            + '              </a>'
            + '              <div class="dropdown-menu btn-block text-center" aria-labelledby="dropdownMenuLink4">'
            + '                <a class="dropdown-item" href="#" onclick="alert()" retrun false;>2017年春期</a>'
            + '                <a class="dropdown-item" href="#" onclick="alert()" retrun false;>2016年春期</a>'
            + '                <a class="dropdown-item" href="#" onclick="alert()" retrun false;>2015年春期</a>'
            + '                <a class="dropdown-item" href="#" onclick="alert()" retrun false;>2014年春期</a>'
            + '                <a class="dropdown-item" href="#" onclick="alert()" retrun false;>2013年春期</a>'
            + '                <a class="dropdown-item" href="#" onclick="alert()" retrun false;>2012年春期</a>'
            + '                <a class="dropdown-item" href="#" onclick="alert()" retrun false;>2011年春期</a>'
            + '              </div>'
            + '            </div>'
            + '        </div>'
            + '      </div>'
            + '      <div class="row">'
            + '          <a href="#" class="d-block h-100">'
            + '              <img class="img-fluid img-thumbnail" src="http://placehold.it/280x300/eeeeee/eeeeee" alt="" />'
            + '          </a>'
            + '      </div>',
        esAm2: '      <h1 id="title01" class="my-4 text-center text-lg-left">平成29年 春期 エンベデッドシステムスペシャリスト</h1>'
            + ''
            + ''
            + '      <!-- Portfolio Item Heading -->'
            + '      <h1 class="my-4">'
            + '        <small id="title02">午前II 問01</small>'
            + '      </h1>'
            + ''
            + '      <!-- Portfolio Item Row -->'
            + '      <div class="row">'
            + ''
            + '        <div class="col-md-8">'
            + '          <p id="question01">スーパスカラの説明はどれか。</p>'
            + '          <p id="question02">A：処理すべきベクトルの長さがベクトルレジスタより長い場合、ベクトルレジスタ長の組に分割して処理を繰り返す方式である。</p>'
            + '          <p id="question03">B：パイプラインを更に細分化することによって、高速化を図る方式である。</p>'
            + '          <p id="question04">C：複数のパイプラインを用い、同時に複数の命令を実行可能にすることによって高速化を図る方式である。</p>'
            + '          <p id="question05">D：命令語を長く取り、一つの命令で複数の機能ユニットを同時に制御することによって高速化を図る方式である。</p>'
            + '          <p id="question06"></p>'
            + '          <p id="question07"></p>'
            + '          <p id="question08"></p>'
            + '          <p id="question09"></p>'
            + '        </div>'
            + ''
            + '        <div class="col-md-4">'
            + '          <p id="selectTitle01">回答</p>'
            + '          <a id="select01" class="btn btn-lg btn-secondary btn-block" href="#" role="button">ア</a>'
            + '          <a id="select02" class="btn btn-lg btn-secondary btn-block" href="#" role="button">イ</a>'
            + '          <a id="select03" class="btn btn-lg btn-secondary btn-block" href="#" role="button">ウ</a>'
            + '          <a id="select04" class="btn btn-lg btn-secondary btn-block" href="#" role="button">エ</a>'
            + '        </div>'
            + ''
            + '      </div>'
            + ''
            + '      <h3 class="my-4">解説</h3>'
            + ''
            + '      <div class="row">'
            + '        <div class="col-md-1"></div>'
            + '        <div class="col-md-11">'
            + '            <p id="result01" class="btn-block">正解</p>'
            + '            <p id="answer01" class="btn-block">答え ウ</p>'
            + ''
            + '          <ul id="guide01" class="list-unstyled" ><li>A：ベクトルプロセッサの説明です</li></ul>'
            + '        </div>'
            + ''
            + '      </div>'
            + ''
            + '      <h3 class="my-4">Related Projects</h3>'
            + ''
            + '      <div class="row">'
            + ''
            + '        <div class="col-md-3 col-sm-6 mb-4">'
            + '          <a id="goTop01" class="btn btn-lg btn-secondary btn-block" href="#" role="button">最初へ</a>'
            + '        </div>'
            + ''
            + '        <div class="col-md-3 col-sm-6 mb-4">'
            + '          <a href="#">'
            + '            <a id="goPrev01" class="btn btn-lg btn-secondary btn-block" href="#" role="button">前へ</a>'
            + '          </a>'
            + '        </div>'
            + ''
            + '        <div class="col-md-3 col-sm-6 mb-4">'
            + '          <a href="#">'
            + '            <a id="goNext01" class="btn btn-lg btn-secondary btn-block" href="#" role="button">次へ</a>'
            + '          </a>'
            + '        </div>'
            + ''
            + '        <div class="col-md-3 col-sm-6 mb-4">'
            + '          <a href="#">'
            + '            <a id="goEnd01" class="btn btn-lg btn-secondary btn-block" href="#" role="button">最後へ</a>'
            + '          </a>'
            + '        </div>'
    };
})(apexam || (apexam = {}));
